import './globals.css';
import type { Metadata } from 'next';
import { Pixelify_Sans, Black_Ops_One } from 'next/font/google';
import ReduxProvider from './redux-provider';

const blackOpsOne = Black_Ops_One({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
    title: 'Pig Game',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={blackOpsOne.className}>
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    );
}
